//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI_DATN_QS.Models.DB_Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANG_DIEM
    {
        public int ID_BangDiem { get; set; }
        public Nullable<int> ID_HocVien { get; set; }
        public Nullable<int> ID_DeThi { get; set; }
        public Nullable<int> DIEM_BangDiem { get; set; }
        public Nullable<int> TGIAN_BangDiem { get; set; }
        public Nullable<int> IS_Deleted { get; set; }
        public Nullable<System.DateTime> TIME_Create { get; set; }
        public Nullable<System.DateTime> TIME_Update { get; set; }
    }
}
