//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI_DATN_QS.Models.DB_Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAU_HOI
    {
        public int ID_CauHoi { get; set; }
        public string NDUNG_CauHoi { get; set; }
        public byte[] ANH_CauHoi { get; set; }
        public string LCHON_1 { get; set; }
        public string LCHON_2 { get; set; }
        public string LCHON_3 { get; set; }
        public string LCHON_4 { get; set; }
        public string LCHON_Dung { get; set; }
        public Nullable<int> ID_Chuong { get; set; }
        public Nullable<int> ID_MonHoc { get; set; }
        public Nullable<int> IS_Deleted { get; set; }
        public Nullable<System.DateTime> TIME_Create { get; set; }
        public Nullable<System.DateTime> TIME_Update { get; set; }
    }
}
