//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI_DATN_QS.Models.DB_Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_DATN_QSEntities : DbContext
    {
        public DB_DATN_QSEntities()
            : base("name=DB_DATN_QSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BANG_DIEM> BANG_DIEM { get; set; }
        public virtual DbSet<CT_DE_THI> CT_DE_THI { get; set; }
        public virtual DbSet<CT_LOP_HOC> CT_LOP_HOC { get; set; }
        public virtual DbSet<HOC_VIEN> HOC_VIEN { get; set; }
        public virtual DbSet<LOAI_BAI_THI> LOAI_BAI_THI { get; set; }
        public virtual DbSet<MON_HOC> MON_HOC { get; set; }
        public virtual DbSet<NGUOI_DUNG> NGUOI_DUNG { get; set; }
        public virtual DbSet<NGANH_HOC> NGANH_HOC { get; set; }
        public virtual DbSet<NIEN_KHOA> NIEN_KHOA { get; set; }
        public virtual DbSet<KHOA_HOC> KHOA_HOC { get; set; }
        public virtual DbSet<LOP_HOC> LOP_HOC { get; set; }
        public virtual DbSet<CAU_HOI> CAU_HOI { get; set; }
        public virtual DbSet<TAI_KHOAN> TAI_KHOAN { get; set; }
        public virtual DbSet<DE_THI> DE_THI { get; set; }
    }
}
