//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI_DATN_QS.Models.DB_Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DE_THI
    {
        public int ID_DeThi { get; set; }
        public string MA_DeThi { get; set; }
        public string TEN_DenThi { get; set; }
        public Nullable<int> ID_LBaiThi { get; set; }
        public Nullable<int> ID_MonHoc { get; set; }
        public string PASS_DeThi { get; set; }
        public Nullable<int> TGIAN_DeThi { get; set; }
        public Nullable<int> IS_Locked { get; set; }
        public Nullable<int> IS_Deleted { get; set; }
        public Nullable<System.DateTime> TIME_Create { get; set; }
        public Nullable<System.DateTime> TIME_Update { get; set; }
    }
}
